# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PasteBin' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PasteBin
  pod 'AFNetworking'
  pod 'DynamicBlurView', '~> 1.3'
  pod 'Highlightr', '~> 2.0'

end
