//
//  SyntaxLibraries.swift
//  PasteBin
//
//  Created by Henrik Gustavii on 04/04/2018.
//  Copyright © 2018 JonLuca De Caro. All rights reserved.
//

import Foundation

struct SyntaxLibraries {
    var languages: [String] = [
        "4CS",
        "6502 ACME Cross Assembler",
        "6502 Kick Assembler",
        "6502 TASM/64TASS",
        "ABAP",
        "ActionScript",
        "ActionScript 3",
        "Ada",
        "AIMMS",
        "ALGOL 68",
        "Apache Log",
        "AppleScript",
        "APT Sources",
        "ARM",
        "ASM (NASM)",
        "ASP",
        "Asymptote",
        "autoconf",
        "Autohotkey",
        "AutoIt",
        "Avisynth",
        "Awk",
        "BASCOM AVR",
        "Bash",
        "Basic4GL",
        "Batch",
        "BibTeX",
        "Blitz Basic",
        "Blitz3D",
        "BlitzMax",
        "BNF",
        "BOO",
        "BrainFuck",
        "C",
        "C (WinAPI)",
        "C for Macs",
        "C Intermediate Language",
        "C#",
        "C++",
        "C++ (WinAPI)",
        "C++ (with Qt extensions)",
        "C: Loadrunner",
        "CAD DCL",
        "CAD Lisp",
        "Ceylon",
        "CFDG",
        "ChaiScript",
        "Chapel",
        "Clojure",
        "Clone C",
        "Clone C++",
        "CMake",
        "COBOL",
        "CoffeeScript",
        "ColdFusion",
        "CSS",
        "Cuesheet",
        "D",
        "Dart",
        "DCL",
        "DCPU-16",
        "DCS",
        "Delphi",
        "Delphi Prism (Oxygene)",
        "Diff",
        "DIV",
        "DOT",
        "E",
        "Easytrieve",
        "ECMAScript",
        "Eiffel",
        "Email",
        "EPC",
        "Erlang",
        "Euphoria",
        "F#",
        "Falcon",
        "Filemaker",
        "FO Language",
        "Formula One",
        "Fortran",
        "FreeBasic",
        "FreeSWITCH",
        "GAMBAS",
        "Game Maker",
        "GDB",
        "Genero",
        "Genie",
        "GetText",
        "Go",
        "Groovy",
        "GwBasic",
        "Haskell",
        "Haxe",
        "HicEst",
        "HQ9 Plus",
        "HTML",
        "HTML 5",
        "Icon",
        "IDL",
        "INI file",
        "Inno Script",
        "INTERCAL",
        "IO",
        "ISPF Panel Definition",
        "J",
        "Java",
        "Java 5",
        "JavaScript",
        "JCL",
        "jQuery",
        "JSON",
        "Julia",
        "KiXtart",
        "Kotlin",
        "Latex",
        "LDIF",
        "Liberty BASIC",
        "Linden Scripting",
        "Lisp", "LLVM",
        "Loco Basic",
        "Logtalk",
        "LOL Code",
        "Lotus Formulas",
        "Lotus Script",
        "LScript",
        "Lua",
        "M68000 Assembler",
        "MagikSF",
        "Make",
        "MapBasic",
        "Markdown",
        "MatLab",
        "mIRC",
        "MIX Assembler",
        "Modula 2",
        "Modula 3",
        "Motorola 68000 HiSoft Dev",
        "MPASM",
        "MXML",
        "MySQL",
        "Nagios",
        "NetRexx",
        "newLISP",
        "Nginx",
        "Nim",
        "None",
        "NullSoft Installer",
        "Oberon 2",
        "Objeck Programming Langua",
        "Objective C",
        "OCalm Brief",
        "OCaml",
        "Octave",
        "Open Object Rexx",
        "OpenBSD PACKET FILTER",
        "OpenGL Shading",
        "Openoffice BASIC",
        "Oracle 11",
        "Oracle 8",
        "Oz",
        "ParaSail",
        "PARI/GP",
        "Pascal",
        "Pawn",
        "PCRE",
        "Per",
        "Perl",
        "Perl 6",
        "PHP",
        "PHP Brief",
        "Pic 16",
        "Pike",
        "Pixel Bender",
        "PL/I",
        "PL/SQL",
        "PostgreSQL",
        "PostScript",
        "POV-Ray",
        "Power Shell",
        "PowerBuilder",
        "ProFTPd",
        "Progress",
        "Prolog",
        "Properties",
        "ProvideX",
        "Puppet",
        "PureBasic",
        "PyCon",
        "Python",
        "Python for S60",
        "q/kdb+",
        "QBasic",
        "QML",
        "R",
        "Racket",
        "Rails",
        "RBScript",
        "REBOL",
        "REG",
        "Rexx",
        "Robots",
        "RPM Spec",
        "Ruby",
        "Ruby Gnuplot",
        "Rust",
        "SAS",
        "Scala",
        "Scheme",
        "Scilab",
        "SCL",
        "SdlBasic",
        "Smalltalk",
        "Smarty",
        "SPARK",
        "SPARQL",
        "SQF",
        "SQL",
        "StandardML",
        "StoneScript",
        "SuperCollider",
        "Swift",
        "SystemVerilog",
        "T-SQL",
        "TCL",
        "Tera Term",
        "thinBasic",
        "TypoScript",
        "Unicon",
        "UnrealScript",
        "UPC",
        "Urbi",
        "Vala",
        "VB.NET",
        "VBScript",
        "Vedit",
        "VeriLog",
        "VHDL",
        "VIM",
        "Visual Pro Log",
        "VisualBasic",
        "VisualFoxPro",
        "WhiteSpace",
        "WHOIS",
        "Winbatch",
        "XBasic",
        "XML",
        "Xorg Config",
        "XPP",
        "YAML",
        "Z80 Assembler",
        "ZXBasic",
    ]

    let highlightrLanguage: [String: String] = [
        "4CS": "default",
        "6502 ACME Cross Assembler": "default",
        "6502 Kick Assembler": "default",
        "6502 TASM/64TASS": "default",
        "ABAP": "default",
        "ActionScript": "actionscript",
        "ActionScript 3": "actionscript",
        "Ada": "ada",
        "AIMMS": "default",
        "ALGOL 68": "default",
        "Apache Log": "apache",
        "AppleScript": "applescript",
        "APT Sources": "default",
        "ARM": "armasm",
        "ASM (NASM)": "armasm",
        "ASP": "default",
        "Asymptote": "default",
        "autoconf": "default",
        "Autohotkey": "autohotkey",
        "AutoIt": "autoit",
        "Avisynth": "default",
        "Awk": "awk",
        "BASCOM AVR": "default",
        "Bash": "bash",
        "Basic4GL": "basic",
        "Batch": "default",
        "BibTeX": "default",
        "Blitz Basic": "basic",
        "Blitz3D": "default",
        "BlitzMax": "default",
        "BNF": "bnf",
        "BOO": "default",
        "BrainFuck": "brainfuck",
        "C": "cpp",
        "C (WinAPI)": "cpp",
        "C for Macs": "cpp",
        "C Intermediate Language": "cpp",
        "C#": "cpp",
        "C++": "cpp",
        "C++ (WinAPI)": "cpp",
        "C++ (with Qt extensions)": "cpp",
        "C: Loadrunner": "cpp",
        "CAD DCL": "default",
        "CAD Lisp": "lisp",
        "Ceylon": "ceylon",
        "CFDG": "default",
        "ChaiScript": "default",
        "Chapel": "default",
        "Clojure": "clojure",
        "Clone C": "cpp",
        "Clone C++": "cpp",
        "CMake": "cmake",
        "COBOL": "default",
        "CoffeeScript": "coffeescript",
        "ColdFusion": "default",
        "CSS": "css",
        "Cuesheet": "default",
        "D": "d",
        "Dart": "dart",
        "DCL": "default",
        "DCPU-16": "default",
        "DCS": "default",
        "Delphi": "delphi",
        "Delphi Prism (Oxygene)": "delphi",
        "Diff": "diff",
        "DIV": "default",
        "DOT": "default",
        "E": "default",
        "Easytrieve": "default",
        "ECMAScript": "javascript",
        "Eiffel": "default",
        "Email": "default",
        "EPC": "default",
        "Erlang": "erlang",
        "Euphoria": "default",
        "F#": "fsharp",
        "Falcon": "default",
        "Filemaker": "default",
        "FO Language": "default",
        "Formula One": "default",
        "Fortran": "fortran",
        "FreeBasic": "default",
        "FreeSWITCH": "default",
        "GAMBAS": "default",
        "Game Maker": "default",
        "GDB": "default",
        "Genero": "default",
        "Genie": "default",
        "GetText": "default",
        "Go": "go",
        "Groovy": "groovy",
        "GwBasic": "default",
        "Haskell": "haskell",
        "Haxe": "haxe",
        "HicEst": "default",
        "HQ9 Plus": "default",
        "HTML": "htmlbars",
        "HTML 5": "htmlbars",
        "Icon": "default",
        "IDL": "default",
        "INI file": "ini",
        "Inno Script": "default",
        "INTERCAL": "default",
        "IO": "default",
        "ISPF Panel Definition": "default",
        "J": "default",
        "Java": "java",
        "Java 5": "java",
        "JavaScript": "javascript",
        "JCL": "default",
        "jQuery": "javascript",
        "JSON": "json",
        "Julia": "julia",
        "KiXtart": "default",
        "Kotlin": "kotlin",
        "Latex": "default",
        "LDIF": "ldif",
        "Liberty BASIC": "basic",
        "Linden Scripting": "default",
        "Lisp": "lisp",
        "LLVM": "llvm",
        "Loco Basic": "basic",
        "Logtalk": "default",
        "LOL Code": "default",
        "Lotus Formulas": "default",
        "Lotus Script": "default",
        "LScript": "livescript",
        "Lua": "lua",
        "M68000 Assembler": "default",
        "MagikSF": "default",
        "Make": "makefile",
        "MapBasic": "default",
        "Markdown": "markdown",
        "MatLab": "matlab",
        "mIRC": "default",
        "MIX Assembler": "default",
        "Modula 2": "default",
        "Modula 3": "default",
        "Motorola 68000 HiSoft Dev": "default",
        "MPASM": "mipsasm",
        "MXML": "default",
        "MySQL": "sql",
        "Nagios": "default",
        "NetRexx": "default",
        "newLISP": "default",
        "Nginx": "nginx",
        "Nim": "nimrod",
        "None": "none",
        "NullSoft Installer": "default",
        "Oberon 2": "default",
        "Objeck Programming Langua": "default",
        "Objective C": "objectivec",
        "OCalm Brief": "ocaml",
        "OCaml": "ocaml",
        "Octave": "default",
        "Open Object Rexx": "default",
        "OpenBSD PACKET FILTER": "default",
        "OpenGL Shading": "default",
        "Openoffice BASIC": "default",
        "Oracle 11": "default",
        "Oracle 8": "default",
        "Oz": "default",
        "ParaSail": "default",
        "PARI/GP": "default",
        "Pascal": "default",
        "Pawn": "default",
        "PCRE": "default",
        "Per": "default",
        "Perl": "perl",
        "Perl 6": "perl",
        "PHP": "php",
        "PHP Brief": "php",
        "Pic 16": "default",
        "Pike": "default",
        "Pixel Bender": "default",
        "PL/I": "default",
        "PL/SQL": "default",
        "PostgreSQL": "default",
        "PostScript": "default",
        "POV-Ray": "default",
        "Power Shell": "powershell",
        "PowerBuilder": "default",
        "ProFTPd": "default",
        "Progress": "default",
        "Prolog": "prolog",
        "Properties": "default",
        "ProvideX": "default",
        "Puppet": "puppet",
        "PureBasic": "purebasic",
        "PyCon": "python",
        "Python": "python",
        "Python for S60": "python",
        "q/kdb+": "q",
        "QBasic": "default",
        "QML": "qml",
        "R": "r",
        "Racket": "default",
        "Rails": "ruby",
        "RBScript": "default",
        "REBOL": "default",
        "REG": "default",
        "Rexx": "default",
        "Robots": "default",
        "RPM Spec": "default",
        "Ruby": "ruby",
        "Ruby Gnuplot": "ruby",
        "Rust": "rust",
        "SAS": "default",
        "Scala": "scala",
        "Scheme": "scheme",
        "Scilab": "scilab",
        "SCL": "default",
        "SdlBasic": "default",
        "Smalltalk": "smalltalk",
        "Smarty": "default",
        "SPARK": "default",
        "SPARQL": "default",
        "SQF": "sqf",
        "SQL": "sql",
        "StandardML": "default",
        "StoneScript": "default",
        "SuperCollider": "default",
        "Swift": "swift",
        "SystemVerilog": "default",
        "T-SQL": "sql",
        "TCL": "tcl",
        "Tera Term": "default",
        "thinBasic": "default",
        "TypoScript": "default",
        "Unicon": "default",
        "UnrealScript": "default",
        "UPC": "default",
        "Urbi": "default",
        "Vala": "vala",
        "VB.NET": "vbnet",
        "VBScript": "vbscript",
        "Vedit": "default",
        "VeriLog": "verilog",
        "VHDL": "vhdl",
        "VIM": "vim",
        "Visual Pro Log": "default",
        "VisualBasic": "default",
        "VisualFoxPro": "default",
        "WhiteSpace": "default",
        "WHOIS": "default",
        "Winbatch": "default",
        "XBasic": "default",
        "XML": "xml",
        "Xorg Config": "default",
        "XPP": "default",
        "YAML": "yaml",
        "Z80 Assembler": "default",
        "ZXBasic": "default",
    ]

    let postLanguage: [String: String] = [
        "4CS": "4cs",
        "6502 ACME Cross Assembler": "6502acme",
        "6502 Kick Assembler": "6502kickass",
        "6502 TASM/64TASS": "6502tasm",
        "ABAP": "abap",
        "ActionScript": "actionscript",
        "ActionScript 3": "actionscript3",
        "Ada": "ada",
        "AIMMS": "aimms",
        "ALGOL 68": "algol68",
        "Apache Log": "apache",
        "AppleScript": "applescript",
        "APT Sources": "apt_sources",
        "ARM": "arm",
        "ASM (NASM)": "asm",
        "ASP": "asp",
        "Asymptote": "asymptote",
        "autoconf": "autoconf",
        "Autohotkey": "autohotkey",
        "AutoIt": "autoit",
        "Avisynth": "avisynth",
        "Awk": "awk",
        "BASCOM AVR": "bascomavr",
        "Bash": "bash",
        "Basic4GL": "basic4gl",
        "Batch": "dos",
        "BibTeX": "bibtex",
        "Blitz Basic": "blitzbasic",
        "Blitz3D": "b3d",
        "BlitzMax": "bmx",
        "BNF": "bnf",
        "BOO": "boo",
        "BrainFuck": "brainfuck",
        "C": "c",
        "C (WinAPI)": "c_winapi",
        "C for Macs": "c_mac",
        "C Intermediate Language": "cil",
        "C#": "csharp",
        "C++": "cpp",
        "C++ (WinAPI)": "cpp-winapi",
        "C++ (with Qt extensions)": "cpp-qt",
        "C: Loadrunner": "c_loadrunner",
        "CAD DCL": "caddcl",
        "CAD Lisp": "cadlisp",
        "Ceylon": "ceylon", // New
        "CFDG": "cfdg",
        "ChaiScript": "chaiscript",
        "Chapel": "chapel",
        "Clojure": "clojure",
        "Clone C": "klonec",
        "Clone C++": "klonecpp",
        "CMake": "cmake",
        "COBOL": "cobol",
        "CoffeeScript": "coffeescript",
        "ColdFusion": "cfm",
        "CSS": "css",
        "Cuesheet": "cuesheet",
        "D": "d",
        "Dart": "dart",
        "DCL": "dcl",
        "DCPU-16": "dcpu16",
        "DCS": "dcs",
        "Delphi": "delphi",
        "Delphi Prism (Oxygene)": "oxygene",
        "Diff": "diff",
        "DIV": "div",
        "DOT": "dot",
        "E": "e",
        "Easytrieve": "ezt",
        "ECMAScript": "ecmascript",
        "Eiffel": "eiffel",
        "Email": "email",
        "EPC": "epc",
        "Erlang": "erlang",
        "Euphoria": "euphoria",
        "F#": "fsharp",
        "Falcon": "falcon",
        "Filemaker": "filemaker",
        "FO Language": "fo",
        "Formula One": "f1",
        "Fortran": "fortran",
        "FreeBasic": "freebasic",
        "FreeSWITCH": "freeswitch",
        "GAMBAS": "gambas",
        "Game Maker": "gml",
        "GDB": "gdb",
        "Genero": "genero",
        "Genie": "genie",
        "GetText": "gettext",
        "Go": "go",
        "Groovy": "groovy",
        "GwBasic": "gwbasic",
        "Haskell": "haskell",
        "Haxe": "haxe",
        "HicEst": "hicest",
        "HQ9 Plus": "hq9plus",
        "HTML": "html4strict",
        "HTML 5": "html5",
        "Icon": "icon",
        "IDL": "idl",
        "INI file": "ini",
        "Inno Script": "inno",
        "INTERCAL": "intercal",
        "IO": "io",
        "ISPF Panel Definition": "ispfpanel",
        "J": "j",
        "Java": "java",
        "Java 5": "java5",
        "JavaScript": "javascript",
        "JCL": "jcl",
        "jQuery": "jquery",
        "JSON": "json",
        "Julia": "julia",
        "KiXtart": "kixtart",
        "Kotlin": "kotlin", // New
        "Latex": "latex",
        "LDIF": "ldif",
        "Liberty BASIC": "lb",
        "Linden Scripting": "lsl2",
        "Lisp": "lisp",
        "LLVM": "llvm",
        "Loco Basic": "locobasic",
        "Logtalk": "logtalk",
        "LOL Code": "lolcode",
        "Lotus Formulas": "lotusformulas",
        "Lotus Script": "lotusscript",
        "LScript": "lscript",
        "Lua": "lua",
        "M68000 Assembler": "m68k",
        "MagikSF": "magiksf",
        "Make": "make",
        "MapBasic": "mapbasic",
        "Markdown": "markdown",
        "MatLab": "matlab",
        "mIRC": "mirc",
        "MIX Assembler": "mmix",
        "Modula 2": "modula2",
        "Modula 3": "modula3",
        "Motorola 68000 HiSoft Dev": "68000devpac",
        "MPASM": "mpasm",
        "MXML": "mxml",
        "MySQL": "mysql",
        "Nagios": "nagios",
        "NetRexx": "netrexx",
        "newLISP": "newlisp",
        "Nginx": "nginx",
        "Nim": "nim", // Changed from Nimrod to Nim
        "None": "text",
        "NullSoft Installer": "nsis",
        "Oberon 2": "oberon2",
        "Objeck Programming Langua": "objeck",
        "Objective C": "objc",
        "OCalm Brief": "ocaml-brief",
        "OCaml": "ocaml",
        "Octave": "octave",
        "Open Object Rexx": "oorexx",
        "OpenBSD PACKET FILTER": "pf",
        "OpenGL Shading": "glsl",
        "Openoffice BASIC": "oobas",
        "Oracle 11": "oracle11",
        "Oracle 8": "oracle8",
        "Oz": "oz",
        "ParaSail": "parasail",
        "PARI/GP": "parigp",
        "Pascal": "pascal",
        "Pawn": "pawn",
        "PCRE": "pcre",
        "Per": "per",
        "Perl": "perl",
        "Perl 6": "perl6",
        "PHP": "php",
        "PHP Brief": "php-brief",
        "Pic 16": "pic16",
        "Pike": "pike",
        "Pixel Bender": "pixelbender",
        "PL/I": "pli",
        "PL/SQL": "plsql",
        "PostgreSQL": "postgresql",
        "PostScript": "postscript",
        "POV-Ray": "povray",
        "Power Shell": "powershell",
        "PowerBuilder": "powerbuilder",
        "ProFTPd": "proftpd",
        "Progress": "progress",
        "Prolog": "prolog",
        "Properties": "properties",
        "ProvideX": "providex",
        "Puppet": "puppet",
        "PureBasic": "purebasic",
        "PyCon": "pycon",
        "Python": "python",
        "Python for S60": "pys60",
        "q/kdb+": "q",
        "QBasic": "qbasic",
        "QML": "qml",
        "R": "rsplus",
        "Racket": "racket",
        "Rails": "rails",
        "RBScript": "rbs",
        "REBOL": "rebol",
        "REG": "reg",
        "Rexx": "rexx",
        "Robots": "robots",
        "RPM Spec": "rpmspec",
        "Ruby": "ruby",
        "Ruby Gnuplot": "gnuplot",
        "Rust": "rust",
        "SAS": "sas",
        "Scala": "scala",
        "Scheme": "scheme",
        "Scilab": "scilab",
        "SCL": "scl",
        "SdlBasic": "sdlbasic",
        "Smalltalk": "smalltalk",
        "Smarty": "smarty",
        "SPARK": "spark",
        "SPARQL": "sparql",
        "SQF": "sqf",
        "SQL": "sql",
        "StandardML": "standardml",
        "StoneScript": "stonescript",
        "SuperCollider": "sclang",
        "Swift": "swift",
        "SystemVerilog": "systemverilog",
        "T-SQL": "tsql",
        "TCL": "tcl",
        "Tera Term": "teraterm",
        "thinBasic": "thinbasic",
        "TypoScript": "typoscript",
        "Unicon": "unicon",
        "UnrealScript": "uscript",
        "UPC": "upc",
        "Urbi": "urbi",
        "Vala": "vala",
        "VB.NET": "vbnet",
        "VBScript": "vbscript",
        "Vedit": "vedit",
        "VeriLog": "verilog",
        "VHDL": "vhdl",
        "VIM": "vim",
        "Visual Pro Log": "visualprolog",
        "VisualBasic": "vb",
        "VisualFoxPro": "visualfoxpro",
        "WhiteSpace": "whitespace",
        "WHOIS": "whois",
        "Winbatch": "winbatch",
        "XBasic": "xbasic",
        "XML": "xml",
        "Xorg Config": "xorg_conf",
        "XPP": "xpp",
        "YAML": "yaml",
        "Z80 Assembler": "z80",
        "ZXBasic": "zxbasic",
    ]
}
